name: STM32 Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: xanderhendriks/action-build-stm32cubeide@v5.0
      with:
        project-path: 'e4e_sleep_timer_fw'
        project-target: 'e4e_sleep_timer_fw'
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          e4e_sleep_timer_fw/Release/e4e_sleep_timer_fw/*